# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cartoipecv2
                                 A QGIS plugin
 descarga shp de IPEC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-17
        copyright            : (C) 2024 by jlmw78
        email                : j@j.j
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cartoipecv2 class from file cartoipecv2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cartoipec_v2 import cartoipecv2
    return cartoipecv2(iface)
